/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface GenericProxyFactoryInterface extends utils.Interface {
  functions: {
    "create(address,bytes)": FunctionFragment;
    "create2(address,bytes32,bytes)": FunctionFragment;
    "predictDeterministicAddress(address,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "create2",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predictDeterministicAddress",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "create2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictDeterministicAddress",
    data: BytesLike
  ): Result;

  events: {
    "ProxyCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProxyCreated"): EventFragment;
}

export type ProxyCreatedEvent = TypedEvent<
  [string, string],
  { created: string; implementation: string }
>;

export type ProxyCreatedEventFilter = TypedEventFilter<ProxyCreatedEvent>;

export interface GenericProxyFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GenericProxyFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    create(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    create2(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    predictDeterministicAddress(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  create(
    _instance: string,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  create2(
    _instance: string,
    _salt: BytesLike,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  predictDeterministicAddress(
    _master: string,
    _salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    create(
      _instance: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    create2(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    predictDeterministicAddress(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ProxyCreated(address,address)"(
      created?: string | null,
      implementation?: string | null
    ): ProxyCreatedEventFilter;
    ProxyCreated(
      created?: string | null,
      implementation?: string | null
    ): ProxyCreatedEventFilter;
  };

  estimateGas: {
    create(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    create2(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    predictDeterministicAddress(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    create2(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    predictDeterministicAddress(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
