/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface GuestProxyFactoryInterface extends utils.Interface {
  functions: {
    "createNewProxy(address,address,address,uint256,uint256,uint256,bytes32)": FunctionFragment;
    "iGenericProxyFactory()": FunctionFragment;
    "iPriceOracle()": FunctionFragment;
    "instance()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createNewProxy",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "iGenericProxyFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "iPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "instance", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createNewProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "iGenericProxyFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "iPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "instance", data: BytesLike): Result;

  events: {};
}

export interface GuestProxyFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GuestProxyFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createNewProxy(
      _wrapper: string,
      _usdc: string,
      _newOwner: string,
      _userDepositCap: BigNumberish,
      _totalDepositCap: BigNumberish,
      _chainId: BigNumberish,
      _guestRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    iGenericProxyFactory(overrides?: CallOverrides): Promise<[string]>;

    iPriceOracle(overrides?: CallOverrides): Promise<[string]>;

    instance(overrides?: CallOverrides): Promise<[string]>;
  };

  createNewProxy(
    _wrapper: string,
    _usdc: string,
    _newOwner: string,
    _userDepositCap: BigNumberish,
    _totalDepositCap: BigNumberish,
    _chainId: BigNumberish,
    _guestRoot: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  iGenericProxyFactory(overrides?: CallOverrides): Promise<string>;

  iPriceOracle(overrides?: CallOverrides): Promise<string>;

  instance(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createNewProxy(
      _wrapper: string,
      _usdc: string,
      _newOwner: string,
      _userDepositCap: BigNumberish,
      _totalDepositCap: BigNumberish,
      _chainId: BigNumberish,
      _guestRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    iGenericProxyFactory(overrides?: CallOverrides): Promise<string>;

    iPriceOracle(overrides?: CallOverrides): Promise<string>;

    instance(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createNewProxy(
      _wrapper: string,
      _usdc: string,
      _newOwner: string,
      _userDepositCap: BigNumberish,
      _totalDepositCap: BigNumberish,
      _chainId: BigNumberish,
      _guestRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    iGenericProxyFactory(overrides?: CallOverrides): Promise<BigNumber>;

    iPriceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    instance(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createNewProxy(
      _wrapper: string,
      _usdc: string,
      _newOwner: string,
      _userDepositCap: BigNumberish,
      _totalDepositCap: BigNumberish,
      _chainId: BigNumberish,
      _guestRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    iGenericProxyFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    iPriceOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    instance(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
