/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  BadgerGuestListAPI,
  BadgerGuestListAPIInterface,
} from "../BadgerGuestListAPI";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "guest",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes32[]",
        name: "merkleProof",
        type: "bytes32[]",
      },
    ],
    name: "authorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_guests",
        type: "address[]",
      },
      {
        internalType: "bool[]",
        name: "_invited",
        type: "bool[]",
      },
    ],
    name: "setGuests",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class BadgerGuestListAPI__factory {
  static readonly abi = _abi;
  static createInterface(): BadgerGuestListAPIInterface {
    return new utils.Interface(_abi) as BadgerGuestListAPIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BadgerGuestListAPI {
    return new Contract(address, _abi, signerOrProvider) as BadgerGuestListAPI;
  }
}
