/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGenericProxyFactory,
  IGenericProxyFactoryInterface,
} from "../IGenericProxyFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_instance",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "instanceCreated",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "result",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGenericProxyFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IGenericProxyFactoryInterface {
    return new utils.Interface(_abi) as IGenericProxyFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGenericProxyFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGenericProxyFactory;
  }
}
