/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IUniswapLPOracleFactory,
  IUniswapLPOracleFactoryInterface,
} from "../IUniswapLPOracleFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_lpToken",
        type: "address",
      },
    ],
    name: "getUnderlyingPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_lpToken",
        type: "address",
      },
    ],
    name: "viewUnderlyingPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUniswapLPOracleFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapLPOracleFactoryInterface {
    return new utils.Interface(_abi) as IUniswapLPOracleFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswapLPOracleFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IUniswapLPOracleFactory;
  }
}
